FROM debian:10.6

USER root
RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak \
    && echo " " > /etc/apt/sources.list \
    && echo "deb http://mirrors.aliyun.com/debian buster main" >> /etc/apt/sources.list \
    && echo "deb http://mirrors.aliyun.com/debian buster-updates main" >> /etc/apt/sources.list \
    && apt-get clean \
    && apt-get update \
    && apt-get install -y gnupg2 wget lsb-release \
    && wget -O - https://files.freeswitch.org/repo/deb/debian-release/fsstretch-archive-keyring.asc | apt-key add - \
    && echo "deb http://files.freeswitch.org/repo/deb/debian-release/ `lsb_release -sc` main" > /etc/apt/sources.list.d/freeswitch.list \
    && echo "deb-src http://files.freeswitch.org/repo/deb/debian-release/ `lsb_release -sc` main" >> /etc/apt/sources.list.d/freeswitch.list \
    && apt-get update && apt-get install -y freeswitch-meta-all